### ISSUE TITLE
SPM build fails with undefined symbol "___llvm_profile_runtime"

### ISSUE THREAD

**Issue by TizianoCoroneo** [segmentio/analytics-ios#906]
iOS Builds using the 4.0.1 prerelease fail with the following error:
```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in Analytics.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This SO question seems relevant: looks like if you have code coverage enabled in your project SPM will inject this flag. I'm not sure if it is something that we could report to Apple, could you give a look?
https://stackoverflow.com/questions/58127940/undefined-symbols-llvm-profile-runtime

**Comment by bsneed** [comment]
cc @migs647

**Comment by migs647** [comment]
@TizianoCoroneo I may need some more information on your build configuration. 
1. How are you adding the Segment Swift Package?
2. Which version of the iOS SDK are you targeting?

If you could put together a demo project that I could use to replicate that would be helpful. I think I'm going down a happy path and not seeing this.

**Comment by TizianoCoroneo** [comment]
[segment-spm-bug.zip](https://github.com/segmentio/analytics-ios/files/4821764/segment-spm-bug.zip)

Small project that reproduces the issue. I just turned on Gather code coverage in the scheme settings.

**Comment by migs647** [comment]
@TizianoCoroneo Thanks so much, diving into it.

**Comment by migs647** [comment]
@TizianoCoroneo We have come to the same conclusion this is a bug with Apple. We suggest disabling the code coverage for now unless you can get the `-fprofile-instr-generate` trick to work (we couldn't). We will keep looking into this including with the new Xcode in hopes this gets resolved by Apple.

**Comment by migs647** [comment]
@TizianoCoroneo Is it possible you can try our current master branch? We changed up our Package.swift to allow swift package to determine to build as dynamic or static. We will put out 4.0.2 soon, but in the mean time you can try that.

**Comment by TizianoCoroneo** [comment]
It works now, thank you!

**Comment by txm5586** [comment]
I recently stumbled with this issue using SPM, 4.1.6 version of Segment. I've try stuff like adding the `-fprofile-instr-generate` flag, but nothing works.
I've my main App Target, and a test target "All Tests" that contains all test targets with coverage enabled for my main target. Just saying this in case it's relevant.
```Undefined symbols for architecture arm64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in Segment.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```
@migs647 Was 4.0.2 supposed to solve this issue? Not sure what to do. I don't really want to disable coverage.

**Comment by txm5586** [comment]
@TizianoCoroneo do you remember doing anything on your side to make this work?

**Comment by TizianoCoroneo** [comment]
No, updating the package was enough. Code coverage works correctly for me now
