### ISSUE TITLE
Cocoapods 0.38.2: error: 'Mixpanel.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by ldiqual** [segmentio/analytics-ios#417]
Using the following pods:

```
pod 'Analytics/Segmentio', '2.0.6'
pod 'Analytics/Mixpanel', '2.0.6'
```

I get the following error:

```
/Users/ldiqual/App/app-ios/Pods/Analytics/Analytics/Integrations/Mixpanel/SEGMixpanelIntegration.m:7:9: error: 'Mixpanel.h' file not found with <angled> include; use "quotes" instead
#import <Mixpanel.h>
        ^~~~~~~~~~~~
        "Mixpanel.h"
1 error generated.
```

The app builds fine with cocoapods `0.38.0`.

Any workaround available?

**Comment by travisjeffery** [comment]
Thanks for the issue. I think this is due to this here: https://github.com/CocoaPods/CocoaPods/issues/3913#issuecomment-128028170, where Cocoapods doesn't support imports like `<Mixpanel.h>` and only `<Mixpanel/Mixpanel.h>`. Just pushed this fix in version 2.0.8.

**Comment by ldiqual** [comment]
@travisjeffery Sweet, thanks for the fix, works great!
