### ISSUE TITLE
Version 0.10.0 linker errors with localytics armv64

### ISSUE THREAD

**Issue by k0nserv** [segmentio/analytics-ios#98]
Hello,

I've ran into some issues with version `0.10.0`, in short it cannot build for all architectures and thus no archiving.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LocalyticsSession", referenced from:
      objc-class-ref in Analytics(LocalyticsProvider.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The same configuration works in `0.9.9`. This was introduced with the new version of localytics in the following [commit](https://github.com/segmentio/analytics-ios/commit/5da8ee83cd5b5b344eebf3f5eca324737e7d3203).

**Comment by Shivagoy** [comment]
i am getting a similar error in my cordova project. How did u fix it

**Comment by Shivagoy** [comment]
I am getting similar error on Xode , please help me fixing this.

**Comment by f2prateek** [comment]
Which version of the library are you using?
